version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: stock_postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - ./stockDatabase:/var/lib/postgresql/data

volumes:
  pgdata: